security:

    encoders:
            App\Entity\User: bcrypt
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
              db_provider:
                  entity:
                      class: App\Entity\User
                      property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: ~
            logout_on_user_change: true
            pattern:    ^/
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: _email
                password_parameter: _password
                default_target_path: homepage
                use_referer: true
                failure_path: login
            logout: true
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_denied_url: /
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
         - { path: ^/(login|register), allow_if: "is_anonymous() and !is_authenticated()" }
         - { path: ^/schedule, role: IS_AUTHENTICATED_FULLY }
         - { path: ^/calendar, role: IS_AUTHENTICATED_FULLY }